# Generated by Django 4.2.28 on 2026-02-17 06:59

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('dialect', models.TextField(default='Pyramid Lake Paiute Tribe')),
                ('writing_system', models.TextField(default='Wycliffe')),
                ('total_pages', models.SmallIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'discs',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.SmallIntegerField(unique=True)),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('page', models.TextField()),
                ('section_title', models.TextField(blank=True, null=True)),
                ('content_tier', models.CharField(choices=[('public', 'Public'), ('tribal_member', 'Tribal Member'), ('educator', 'Educator'), ('admin', 'Admin')], default='tribal_member', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='numu.disc')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiute', models.TextField()),
                ('paiute_normalized', models.TextField(unique=True)),
                ('is_multi_sense', models.BooleanField(default=False)),
                ('needs_lexeme_review', models.BooleanField(default=False)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lexemes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('display_name', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('public', 'Public'), ('tribal_member', 'Tribal Member'), ('educator', 'Educator'), ('admin', 'Admin')], default='public', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('tribal_enrollment_number', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='VerbPhraseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiute', models.TextField()),
                ('english', models.TextField()),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verb_phrase_forms', to='numu.lesson')),
            ],
            options={
                'db_table': 'verb_phrase_forms',
                'ordering': ['lesson', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VerbParadigmForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiute', models.TextField()),
                ('pronunciation', models.TextField(blank=True, null=True)),
                ('english', models.TextField()),
                ('grammatical_tags', models.JSONField(blank=True, null=True)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_verb_lexeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verb_paradigm_forms', to='numu.lexeme')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verb_paradigm_forms', to='numu.lesson')),
            ],
            options={
                'db_table': 'verb_paradigm_forms',
                'ordering': ['lesson', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SuffixExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=20)),
                ('base_verb', models.TextField()),
                ('base_verb_english', models.TextField(blank=True, null=True)),
                ('suffixed_form', models.TextField()),
                ('english', models.TextField()),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_verb_lexeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suffix_examples', to='numu.lexeme')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suffix_examples', to='numu.lesson')),
            ],
            options={
                'db_table': 'suffix_examples',
                'ordering': ['lesson', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SentenceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiute', models.TextField()),
                ('english', models.TextField()),
                ('components', models.JSONField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentence_entries', to='numu.lesson')),
            ],
            options={
                'db_table': 'sentence_entries',
                'ordering': ['lesson', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PrayerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.SmallIntegerField()),
                ('paiute', models.TextField()),
                ('english', models.TextField()),
                ('is_ritual_action', models.BooleanField(default=False)),
                ('ritual_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prayer_lines', to='numu.lesson')),
            ],
            options={
                'db_table': 'prayer_lines',
                'ordering': ['lesson', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='NumberEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiute', models.TextField()),
                ('english', models.TextField()),
                ('numeral', models.SmallIntegerField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('base', 'Base'), ('compound', 'Compound')], max_length=10)),
                ('components', models.TextField(blank=True, null=True)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_entries', to='numu.lesson')),
            ],
            options={
                'db_table': 'number_entries',
                'ordering': ['lesson', 'numeral', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiute', models.TextField()),
                ('pronunciation', models.TextField(blank=True, null=True)),
                ('english', models.TextField()),
                ('context_note', models.TextField(blank=True, null=True)),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='numu.lesson')),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='numu.lexeme')),
            ],
            options={
                'db_table': 'entries',
                'ordering': ['lesson', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ColorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.TextField()),
                ('adjective', models.TextField()),
                ('predicate', models.TextField()),
                ('predicate_gloss', models.TextField()),
                ('noun_form', models.TextField()),
                ('noun_gloss', models.TextField()),
                ('extra_forms', models.JSONField(blank=True, null=True)),
                ('compound_components', models.TextField(blank=True, null=True)),
                ('compound_result', models.TextField(blank=True, null=True)),
                ('compound_english', models.TextField(blank=True, null=True)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_forms', to='numu.lesson')),
            ],
            options={
                'db_table': 'color_forms',
                'ordering': ['lesson', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ColorExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiute', models.TextField()),
                ('english', models.TextField()),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('color_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_sentences', to='numu.colorform')),
            ],
            options={
                'db_table': 'color_example_sentences',
                'ordering': ['color_form', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ColorApplicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_number', models.SmallIntegerField()),
                ('paiute', models.TextField()),
                ('english', models.TextField()),
                ('source_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='color_application_entries', to='numu.lesson')),
            ],
            options={
                'db_table': 'color_application_entries',
                'ordering': ['lesson', 'source_number'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('s3_key', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_files', to='numu.entry')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audio_files', to='numu.lesson')),
            ],
            options={
                'db_table': 'audio_files',
            },
        ),
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paiute', models.TextField()),
                ('english', models.TextField()),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal_categories', to='numu.lesson')),
            ],
            options={
                'db_table': 'animal_categories',
                'ordering': ['lesson', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_progress', to='numu.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='numu.user')),
            ],
            options={
                'db_table': 'user_lesson_progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserEntryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('correct', models.BooleanField()),
                ('ease_factor', models.DecimalField(decimal_places=2, default=2.5, max_digits=4)),
                ('interval_days', models.SmallIntegerField(default=1)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_reviews', to='numu.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_reviews', to='numu.user')),
            ],
            options={
                'db_table': 'user_entry_reviews',
                'unique_together': {('user', 'entry')},
            },
        ),
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('flag_note', models.TextField()),
                ('source', models.CharField(choices=[('transcription', 'Transcription'), ('audio', 'Audio'), ('import', 'Import'), ('manual', 'Manual')], default='transcription', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to='numu.user')),
            ],
            options={
                'db_table': 'review_flags',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='review_flag_content_575e96_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='audiofile',
            constraint=models.CheckConstraint(check=models.Q(('lesson__isnull', False), ('entry__isnull', False), _connector='OR'), name='audio_has_parent'),
        ),
    ]
