# Generated by Django on 2026-03-09

from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def migrate_grammar_tables(apps, schema_editor):
    """
    Migrate all specialized grammar tables into the unified Entry table.
    """
    Entry = apps.get_model('numu', 'Entry')
    ReviewFlag = apps.get_model('numu', 'ReviewFlag')
    
    id_mapping = {}
    stats = {}

    # 1. VerbParadigmForm
    VerbParadigmForm = apps.get_model('numu', 'VerbParadigmForm')
    vpf_old_ct = ContentType.objects.get_for_model(VerbParadigmForm)
    count = 0
    for vpf in VerbParadigmForm.objects.all():
        metadata = {}
        if vpf.grammatical_tags:
            metadata['grammatical_tags'] = vpf.grammatical_tags
        if vpf.base_verb_lexeme_id:
            metadata['base_verb_lexeme_id'] = vpf.base_verb_lexeme_id
        
        entry = Entry.objects.create(
            lesson=vpf.lesson,
            lexeme=None,
            paiute=vpf.paiute,
            pronunciation=vpf.pronunciation,
            english=vpf.english,
            sort_order=vpf.sort_order,
            source_notes=vpf.source_notes,
            content_type='verb_form',
            metadata=metadata,
        )
        id_mapping[('VerbParadigmForm', vpf.id)] = entry.id
        count += 1
    stats['verb_paradigm_forms'] = count

    # 2. VerbPhraseForm
    VerbPhraseForm = apps.get_model('numu', 'VerbPhraseForm')
    vphr_old_ct = ContentType.objects.get_for_model(VerbPhraseForm)
    count = 0
    for vphr in VerbPhraseForm.objects.all():
        entry = Entry.objects.create(
            lesson=vphr.lesson,
            lexeme=None,
            paiute=vphr.paiute,
            english=vphr.english,
            sort_order=vphr.sort_order,
            source_notes=vphr.source_notes,
            content_type='verb_phrase',
            metadata={},
        )
        id_mapping[('VerbPhraseForm', vphr.id)] = entry.id
        count += 1
    stats['verb_phrase_forms'] = count

    # 3. ColorForm
    ColorForm = apps.get_model('numu', 'ColorForm')
    cf_old_ct = ContentType.objects.get_for_model(ColorForm)
    count = 0
    for cf in ColorForm.objects.all():
        metadata = {
            'adjective': cf.adjective,
            'predicate': cf.predicate,
            'predicate_gloss': cf.predicate_gloss,
            'noun_form': cf.noun_form,
            'noun_gloss': cf.noun_gloss,
        }
        if cf.extra_forms:
            metadata['extra_forms'] = cf.extra_forms
        if cf.compound_components:
            metadata['compound_components'] = cf.compound_components
        if cf.compound_result:
            metadata['compound_result'] = cf.compound_result
        if cf.compound_english:
            metadata['compound_english'] = cf.compound_english
        
        # Get example sentences
        ColorExampleSentence = apps.get_model('numu', 'ColorExampleSentence')
        examples = list(ColorExampleSentence.objects.filter(color_form=cf).values(
            'paiute', 'english', 'sort_order'
        ))
        if examples:
            metadata['examples'] = examples
        
        entry = Entry.objects.create(
            lesson=cf.lesson,
            lexeme=None,
            paiute=cf.adjective,
            english=cf.english,
            sort_order=cf.sort_order,
            source_notes=cf.source_notes,
            content_type='color_form',
            metadata=metadata,
        )
        id_mapping[('ColorForm', cf.id)] = entry.id
        count += 1
    stats['color_forms'] = count

    # 4. SuffixExample
    SuffixExample = apps.get_model('numu', 'SuffixExample')
    se_old_ct = ContentType.objects.get_for_model(SuffixExample)
    count = 0
    for se in SuffixExample.objects.all():
        metadata = {
            'suffix': se.suffix,
            'base_verb': se.base_verb,
        }
        if se.base_verb_english:
            metadata['base_verb_english'] = se.base_verb_english
        if se.base_verb_lexeme_id:
            metadata['base_verb_lexeme_id'] = se.base_verb_lexeme_id
        
        entry = Entry.objects.create(
            lesson=se.lesson,
            lexeme=None,
            paiute=se.suffixed_form,
            english=se.english,
            sort_order=se.sort_order,
            source_notes=se.source_notes,
            content_type='suffix_example',
            metadata=metadata,
        )
        id_mapping[('SuffixExample', se.id)] = entry.id
        count += 1
    stats['suffix_examples'] = count

    # 5. SentenceEntry - PRESERVE EMBEDDINGS
    SentenceEntry = apps.get_model('numu', 'SentenceEntry')
    sent_old_ct = ContentType.objects.get_for_model(SentenceEntry)
    count = 0
    for sent in SentenceEntry.objects.all():
        metadata = {}
        if sent.components:
            metadata['components'] = sent.components
        
        entry = Entry.objects.create(
            lesson=sent.lesson,
            lexeme=None,
            paiute=sent.paiute,
            english=sent.english,
            sort_order=sent.sort_order,
            source_notes=sent.source_notes,
            content_type='sentence',
            metadata=metadata,
            embedding=sent.embedding,
        )
        id_mapping[('SentenceEntry', sent.id)] = entry.id
        count += 1
    stats['sentence_entries'] = count

    # 6. PrayerLine
    PrayerLine = apps.get_model('numu', 'PrayerLine')
    pl_old_ct = ContentType.objects.get_for_model(PrayerLine)
    count = 0
    for pl in PrayerLine.objects.all():
        metadata = {
            'line_number': pl.line_number,
            'is_ritual_action': pl.is_ritual_action,
        }
        if pl.ritual_note:
            metadata['ritual_note'] = pl.ritual_note
        
        entry = Entry.objects.create(
            lesson=pl.lesson,
            lexeme=None,
            paiute=pl.paiute,
            english=pl.english,
            sort_order=pl.line_number,
            content_type='prayer_line',
            metadata=metadata,
        )
        id_mapping[('PrayerLine', pl.id)] = entry.id
        count += 1
    stats['prayer_lines'] = count

    # 7. NumberEntry
    NumberEntry = apps.get_model('numu', 'NumberEntry')
    ne_old_ct = ContentType.objects.get_for_model(NumberEntry)
    count = 0
    for ne in NumberEntry.objects.all():
        metadata = {
            'numeral': ne.numeral,
            'entry_type': ne.entry_type,
        }
        if ne.components:
            metadata['components'] = ne.components
        
        entry = Entry.objects.create(
            lesson=ne.lesson,
            lexeme=None,
            paiute=ne.paiute,
            english=ne.english,
            sort_order=ne.sort_order,
            source_notes=ne.source_notes,
            content_type='number',
            metadata=metadata,
        )
        id_mapping[('NumberEntry', ne.id)] = entry.id
        count += 1
    stats['number_entries'] = count

    # 8. AnimalCategory
    AnimalCategory = apps.get_model('numu', 'AnimalCategory')
    ac_old_ct = ContentType.objects.get_for_model(AnimalCategory)
    count = 0
    for ac in AnimalCategory.objects.all():
        entry = Entry.objects.create(
            lesson=ac.lesson,
            lexeme=None,
            paiute=ac.paiute,
            english=ac.english,
            sort_order=ac.sort_order,
            content_type='animal_category',
            metadata={},
        )
        id_mapping[('AnimalCategory', ac.id)] = entry.id
        count += 1
    stats['animal_categories'] = count

    # 9. ColorApplicationEntry
    ColorApplicationEntry = apps.get_model('numu', 'ColorApplicationEntry')
    cae_old_ct = ContentType.objects.get_for_model(ColorApplicationEntry)
    count = 0
    for cae in ColorApplicationEntry.objects.all():
        metadata = {
            'source_number': cae.source_number,
        }
        
        entry = Entry.objects.create(
            lesson=cae.lesson,
            lexeme=None,
            paiute=cae.paiute,
            english=cae.english,
            sort_order=cae.source_number,
            source_notes=cae.source_notes,
            content_type='color_usage',
            metadata=metadata,
        )
        id_mapping[('ColorApplicationEntry', cae.id)] = entry.id
        count += 1
    stats['color_application_entries'] = count

    # 10. Remap ReviewFlags
    entry_ct = ContentType.objects.get_for_model(Entry)
    ct_to_model = {
        vpf_old_ct.id: 'VerbParadigmForm',
        vphr_old_ct.id: 'VerbPhraseForm',
        cf_old_ct.id: 'ColorForm',
        se_old_ct.id: 'SuffixExample',
        sent_old_ct.id: 'SentenceEntry',
        pl_old_ct.id: 'PrayerLine',
        ne_old_ct.id: 'NumberEntry',
        ac_old_ct.id: 'AnimalCategory',
        cae_old_ct.id: 'ColorApplicationEntry',
    }
    
    flag_remap_count = 0
    for flag in ReviewFlag.objects.filter(content_type_id__in=ct_to_model.keys()):
        old_model_name = ct_to_model[flag.content_type_id]
        key = (old_model_name, flag.object_id)
        
        if key in id_mapping:
            flag.content_type_id = entry_ct.id
            flag.object_id = id_mapping[key]
            flag.save(update_fields=['content_type_id', 'object_id'])
            flag_remap_count += 1
    
    stats['review_flags_remapped'] = flag_remap_count

    print("\nMigration 0004 Stats:")
    for table, count in stats.items():
        print(f"  {table}: {count}")


def reverse_migration(apps, schema_editor):
    Entry = apps.get_model('numu', 'Entry')
    content_types = [
        'verb_form', 'verb_phrase', 'color_form', 'suffix_example',
        'sentence', 'prayer_line', 'number', 'animal_category', 'color_usage'
    ]
    deleted_count = Entry.objects.filter(content_type__in=content_types).delete()[0]
    print(f"\nReversed: Deleted {deleted_count} Entry rows")


class Migration(migrations.Migration):
    dependencies = [
        ('numu', '0003_backfill_courses'),
    ]

    operations = [
        migrations.RunPython(migrate_grammar_tables, reverse_migration),
    ]