# Generated by Django on 2026-03-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numu', '0004_migrate_grammar_to_entry'),
    ]

    operations = [
        # Drop child table first (foreign key dependency)
        migrations.DeleteModel(
            name='ColorExampleSentence',
        ),
        
        # Drop all specialized grammar tables
        migrations.DeleteModel(
            name='VerbParadigmForm',
        ),
        migrations.DeleteModel(
            name='VerbPhraseForm',
        ),
        migrations.DeleteModel(
            name='ColorForm',
        ),
        migrations.DeleteModel(
            name='SuffixExample',
        ),
        migrations.DeleteModel(
            name='SentenceEntry',
        ),
        migrations.DeleteModel(
            name='PrayerLine',
        ),
        migrations.DeleteModel(
            name='NumberEntry',
        ),
        migrations.DeleteModel(
            name='AnimalCategory',
        ),
        migrations.DeleteModel(
            name='ColorApplicationEntry',
        ),
    ]